### ISSUE TITLE
include mtl & transformers ?

### ISSUE THREAD

**Issue by afcady** [nikita-volkov/rebase#1]
Seems reasonable to me.  

Btw, top 15 packages by reverse dependencies are:

```
base                  9124
bytestring            3321
containers            3130
mtl                   2480
text                  2181
transformers          1876
directory             1608
filepath              1417
time                  1270
QuickCheck            1157
process               957
vector                873
array                 866
template-haskell      840
parsec                786
```

**Comment by nikita-volkov** [comment]
I've considered that, but I'm not certain yet. Maybe let's take a little time and get some input from other users? Let's have a vote on this.

**Comment by nikita-volkov** [comment]
I've added "transformers" so far.

**Comment by guaraqe** [comment]
The `either` package uses `mtl`, so the dependency is already there. And I see many places recommending its paradigm of creating classes and deciding an implementation later, which would go in hand with the "current practices" spirit of the package.

The `free` package is already used by `either` too, and I saw someone asking for it on reddit. But that's just for info, as I have no experience with it.

**Comment by nikita-volkov** [comment]
@guaraqe Okay! I'd accept the according pull requests.

**Comment by nikita-volkov** [comment]
Implemented
