### ISSUE TITLE
rebase currently broken on Stackage

### ISSUE THREAD

**Issue by cdornan** [nikita-volkov/rebase#11]
rebase is currently broken on Stackage failing to build with the following error so we have disabled it to make the release . Could you let us know when it is fixed so we ca restore it &mdash; cheers.

---

library/Rebase/Prelude.hs:9:3: error:
    Conflicting exports for ‘optional’:
       ‘module Exports’ exports ‘Exports.optional’
         imported from ‘BasePrelude’ at library/Rebase/Prelude.hs:16:1-63
         (and originally defined in ‘Control.Applicative’)
       ‘module Exports’ exports ‘Exports.optional’
         imported from ‘Rebase.Data.Functor.Plus’ at library/Rebase/Prelude.hs:53:1-68
         (and originally defined in ‘Data.Functor.Alt’)

**Comment by felixonmars** [comment]
This has been fixed in 1.2.3.

**Comment by mihaimaruseac** [comment]
Fix confirmed, this can be closed.
