### ISSUE TITLE
Is there a reason sortOn is hidden in the prelude?

### ISSUE THREAD

**Issue by galenhuntington** [nikita-volkov/rebase#15]
As of this commit

https://github.com/nikita-volkov/rebase/commit/a64a4afbdb142a99ed77aa9c28197ff8bf417932#diff-cb343bc1e60d12ff35c4afd02db6a091R45

the three list functions `sortOn`, `isSubsequenceOf`, and `uncons` are no longer available in the prelude since they are hidden.  But they don't conflict with any other exports, so was their removal intentional?

**Comment by nikita-volkov** [comment]
Oh. No, it wasn't. Just a consequence of removing the "base-prelude" dep. I'll fix that.

**Comment by nikita-volkov** [comment]
Fixed in 1.6
